### ISSUE TITLE
The registration name of the item is misplaced

### ISSUE THREAD

**Issue by MCTF-Alpha-27** [ConnorTron110/SCP-Lockdown-Issues#14]
When I am exporting JSON of items for MC百科(mcmod.cn)，I found the registration name of the item is misplaced.

Maybe you want to ask me why I need the JSON file and what is MC百科(mcmod.cn).
MC百科(mcmod.cn) is a Minecraft Chinese wiki, I need to upload a JSON file to update the items and introduce them.

**Comment by ConnorTron110** [comment]
A Json? What like a Language File?

**Comment by MCTF-Alpha-27** [comment]
It is a list of items in your MOD, I need this file to upload to MC百科, but I found the registration name of the item is misplaced, so I cannot export it.
Do you know how to slove it?

**Comment by ConnorTron110** [comment]
Are you trying to find the Registry of the Items in the code? If so I cannot tell you as the Code is closed src, you can decompile it and search the classes yourself but it will be hard to navigate to them.
Since this isnt really a bug i will have to close this, however if you still need help with this or have any other questions please head over to our [Discord](https://discord.gg/NGdHJzh)

**Comment by MCTF-Alpha-27** [comment]
It's actually not a file in your MOD already, I use another MOD called item reader to export it.
