### ISSUE TITLE
Facilities Spawn Floating

### ISSUE THREAD

**Issue by DarianLStephens** [ConnorTron110/SCP-Lockdown-Issues#21]
A couple of times in a test world, we found SCP facilities floating above the ground.
![2022-01-17_08 15 52](https://user-images.githubusercontent.com/15375876/149683876-e166fcab-fc44-48f6-9f8e-cce7525962ee.png)

From what we can tell, it spawned on top of the hill to the right there, and just kept going.
If there was a way to get the average height of the surrounding terrain for the main facility, and build underneath to fill in gaps, that would help out a lot.

Also, if there was some way to add an option that makes the facilities spawn underground, preferably below a given Y coordinate in the config, that would be fantastic for the feel of our server.

**Comment by ConnorTron110** [comment]
Hello, yes this is due to the sheer size of the facilities, sometimes we have these facilities spawn underwater or even clip into the ocean. Having the average height calculated should not be too much of a challenge however the current implementation is meant to be as computationally inexpensive as possible (not that it already doesn't affect slow computers).
I do like the idea of fixing the height at which these facilities spawn, however having something underneath them may add more time to the process, Thanks for the suggestion!

I'm going to count this as a Bug as its unintended and unwanted behaviour, however, I'm gonna treat this thread as a suggestion as nothing game-breaking comes from it spawning like this.

**Comment by ConnorTron110** [comment]
Since the structure generation code was re-written by Alexiy (one of the previous developers) due to the sheer size of the facility, I will leave it as it is, as frustrating as it is visually I will probably leave this issue to be fixed in 3.0. Thanks for your understanding.
