### ISSUE TITLE
MineMenu Starts lagging like a bich with SCP Lockdown

### ISSUE THREAD

**Issue by CygnusThe1st** [ConnorTron110/SCP-Lockdown-Issues#42]
Specifically the Icon Selection menu and the game might as well crash when typing something into the Item Selector's search bar

**Comment by ConnorTron110** [comment]
I’m not experiencing major lag spikes on the icon selection screen, but this may be because I have only MineMenu and SCPLockdown installed to test.

It’s possible you are just experiencing a symptom of not having enough ram dedicated and or just a lot of mods. It’s not necessarily SCPLockdown's fault as the search function would not be interfered by Lockdown itself.

Ill mark this issue closed and not ours for the time being as I cannot see Lockdown causing the lag spikes on searching function. Ill reopen it if more context gets provided, IE RAM usage, mods loaded etc.
